<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\ProshoreBuildArtifacts\$(MSBuildProjectName)\obj\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\ProshoreBuildArtifacts\$(MSBuildProjectName)\bin\</BaseOutputPath>
  </PropertyGroup>
</Project>
